[workspace]
authors = ["izkf_pack"]
channels = ["conda-forge", "bioconda"]
name = "nfcore_3mrnaseq"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
nextflow = "*"

[tasks]
run-local = "python3 run.py"
test = "python3 test.py"
