#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import shutil
import shlex
from pathlib import Path


GENOME_PLACEHOLDER = "__EDIT_ME_GENOME__"
UMI_KIT = "UMI Second Strand SynthesisModule for QuantSeq FWD"
SPIKEIN_KIT = "ERCC RNA Spike-in Mix"
TRUTHY_VALUES = {"1", "true", "yes", "on"}
FALSY_VALUES = {"0", "false", "no", "off", "none", "null", "na", "n/a"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prepare the nf-core/rnaseq workspace.")
    parser.add_argument(
        "--prepare",
        "--prepare-only",
        action="store_true",
        help="Copy samplesheet.csv and write config/run_params.env.",
    )
    return parser.parse_args()


def require_env(name: str) -> str:
    value = os.environ.get(name, "").strip()
    if not value:
        raise SystemExit(f"[error] required environment variable is missing: {name}")
    return value


def optional_env(name: str, default: str = "") -> str:
    return os.environ.get(name, default).strip()


def normalize_toggle_param(value: str, *, enabled_value: str) -> str:
    normalized = value.strip()
    if not normalized:
        return ""
    lowered = normalized.lower()
    if lowered in TRUTHY_VALUES:
        return enabled_value
    if lowered in FALSY_VALUES:
        return ""
    return normalized


def normalize_memory(value: str) -> str:
    memory = value.strip()
    if memory.upper().endswith("GB"):
        return f"{memory[:-2]}.GB"
    return memory


def effective_genome(genome: str, spikein: str) -> str:
    if genome == GENOME_PLACEHOLDER:
        return genome
    if spikein and "ERCC" in spikein:
        return f"{genome}_with_ERCC"
    return genome


def shell_assign(name: str, value: str) -> str:
    return f"{name}={shlex.quote(value)}"


def copy_samplesheet(source: Path, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    if source.resolve() == destination.resolve():
        return
    shutil.copy2(source, destination)


def write_runtime_env(
    output_path: Path,
    *,
    genome: str,
    effective: str,
    umi: str,
    spikein: str,
    max_cpus: str,
    max_memory: str,
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by run.py. Edit values here before rerunning.",
        shell_assign("GENOME", genome),
        shell_assign("EFFECTIVE_GENOME", effective),
        shell_assign("UMI", umi),
        shell_assign("SPIKEIN", spikein),
        shell_assign("MAX_CPUS", str(max_cpus)),
        shell_assign("MAX_MEMORY", normalize_memory(max_memory) if max_memory else ""),
        "",
    ]
    output_path.write_text("\n".join(lines), encoding="utf-8")


def prepare() -> None:
    script_dir = Path(__file__).resolve().parent
    genome = require_env("GENOME")
    spikein = normalize_toggle_param(optional_env("SPIKEIN"), enabled_value=SPIKEIN_KIT)
    umi = normalize_toggle_param(optional_env("UMI"), enabled_value=UMI_KIT)
    max_cpus = optional_env("MAX_CPUS")
    max_memory = optional_env("MAX_MEMORY")

    copy_samplesheet(Path(require_env("SAMPLESHEET")).resolve(), script_dir / "samplesheet.csv")
    run_params = script_dir / "config" / "run_params.env"
    write_runtime_env(
        run_params,
        genome=genome,
        effective=effective_genome(genome, spikein),
        umi=umi,
        spikein=spikein,
        max_cpus=max_cpus,
        max_memory=max_memory,
    )
    print(f"[info] wrote {run_params.relative_to(script_dir)}", flush=True)


def main() -> int:
    parse_args()
    prepare()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
