#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Materialize resolved Linkar inputs for dgea_interaction.")
    parser.add_argument("--workspace-dir", required=True)
    parser.add_argument("--results-dir", required=True)
    parser.add_argument("--salmon-dir", required=True)
    parser.add_argument("--samplesheet", required=True)
    parser.add_argument("--organism", required=True)
    parser.add_argument("--application", default="")
    parser.add_argument("--name", default="")
    parser.add_argument("--authors", default="")
    parser.add_argument("--use-llm", default="true")
    parser.add_argument("--llm-config", default="")
    parser.add_argument("--llm-base-url", default="")
    parser.add_argument("--llm-model", default="")
    parser.add_argument("--llm-temperature", default="0.2")
    return parser.parse_args()


def existing_path(value: str, label: str, *, directory: bool = False, required: bool = True) -> str:
    if not value.strip():
        if required:
            raise SystemExit(f"{label} is required.")
        return ""
    path = Path(value).expanduser().resolve()
    valid = path.is_dir() if directory else path.is_file()
    if not valid:
        raise SystemExit(f"{label} does not exist: {path}")
    return str(path)


def r_assignment(name: str, value: object) -> str:
    if isinstance(value, bool):
        return f"{name} <- {'TRUE' if value else 'FALSE'}"
    if value is None:
        return f"{name} <- NULL"
    return f"{name} <- {json.dumps(value, ensure_ascii=False)}"


def parse_bool(value: str) -> bool:
    return value.strip().lower() in {"1", "true", "yes", "y", "on"}


def main() -> int:
    args = parse_args()
    workspace = Path(args.workspace_dir).resolve()
    results = Path(args.results_dir).resolve()
    workspace.mkdir(parents=True, exist_ok=True)
    results.mkdir(parents=True, exist_ok=True)
    salmon_dir = existing_path(args.salmon_dir, "salmon_dir", directory=True)
    samplesheet = existing_path(args.samplesheet, "samplesheet")
    tx2gene = Path(salmon_dir) / "salmon.merged.tx2gene.tsv"
    if not tx2gene.is_file():
        raise SystemExit(f"tx2gene mapping does not exist: {tx2gene}")
    llm_config = existing_path(args.llm_config, "llm_config", required=False)
    values: dict[str, object] = {
        "workspace_dir": str(workspace),
        "results_dir": str(results),
        "salmon_dir": salmon_dir,
        "samplesheet_path": samplesheet,
        "tx2gene_file": str(tx2gene.resolve()),
        "organism": args.organism.strip(),
        "application": args.application.strip(),
        "project_name": args.name.strip() or workspace.parent.name,
        "authors": args.authors.strip(),
        "use_llm": parse_bool(args.use_llm),
        "llm_config": llm_config,
        "llm_base_url": args.llm_base_url.strip(),
        "llm_model": args.llm_model.strip(),
        "llm_temperature": float(args.llm_temperature),
    }
    (workspace / "dgea_interaction_inputs.R").write_text(
        "# Generated by build_dgea_inputs.py. Do not edit.\n"
        + "\n".join(r_assignment(key, value) for key, value in values.items())
        + "\n",
        encoding="utf-8",
    )
    run_info = {
        "template": "dgea_interaction",
        "template_version": "0.1.1",
        "params": {
            "salmon_dir": salmon_dir,
            "samplesheet": samplesheet,
            "organism": values["organism"],
            "application": values["application"],
            "name": values["project_name"],
            "authors": values["authors"],
            "use_llm": values["use_llm"],
            "llm_model": values["llm_model"],
        },
    }
    try:
        import yaml

        text = yaml.safe_dump(run_info, sort_keys=False, allow_unicode=True)
    except ImportError:
        text = json.dumps(run_info, indent=2, ensure_ascii=False) + "\n"
    (results / "run_info.yaml").write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
