#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

import yaml


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Write DGEA runtime inputs for the Linkar DGEA template.")
    parser.add_argument("--workspace-dir", default=".")
    parser.add_argument("--results-dir", default="./results")
    parser.add_argument("--salmon-dir", required=True)
    parser.add_argument("--samplesheet", required=True)
    parser.add_argument("--organism", required=True)
    parser.add_argument("--spikein", default="")
    parser.add_argument("--application", default="")
    parser.add_argument("--name", default="")
    parser.add_argument("--authors", default="")
    return parser.parse_args()


def r_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def write_inputs_r(path: Path, args: argparse.Namespace) -> None:
    path.write_text(
        "\n".join(
            [
                "# Auto-generated by build_dgea_inputs.py",
                f"salmon_dir <- {r_string(str(Path(args.salmon_dir).resolve()))}",
                f"samplesheet_path <- {r_string(str(Path(args.samplesheet).resolve()))}",
                f'organism <- {r_string(args.organism)}',
                f'spikein <- {r_string(args.spikein)}',
                f'application <- {r_string(args.application)}',
                f'project_name <- {r_string(args.name)}',
                f'authors <- {r_string(args.authors)}',
                'tx2gene_file <- file.path(salmon_dir, "tx2gene.tsv")',
                f'results_dir <- {r_string(str(Path(args.results_dir).resolve()))}',
                'dir.create(results_dir, recursive = TRUE, showWarnings = FALSE)',
                "",
            ]
        ),
        encoding="utf-8",
    )


def write_run_info(path: Path, args: argparse.Namespace) -> None:
    data = {
        "params": {
            "salmon_dir": str(Path(args.salmon_dir).resolve()),
            "samplesheet": str(Path(args.samplesheet).resolve()),
            "organism": args.organism,
            "spikein": args.spikein,
            "application": args.application,
            "name": args.name,
            "authors": args.authors,
        },
        "workspace_dir": str(Path(args.workspace_dir).resolve()),
        "results_dir": str(Path(args.results_dir).resolve()),
    }
    path.write_text(yaml.safe_dump(data, sort_keys=False), encoding="utf-8")


def main() -> int:
    args = parse_args()
    workspace_dir = Path(args.workspace_dir).resolve()
    results_dir = Path(args.results_dir).resolve()
    workspace_dir.mkdir(parents=True, exist_ok=True)
    results_dir.mkdir(parents=True, exist_ok=True)
    write_inputs_r(workspace_dir / "dgea_inputs.R", args)
    write_run_info(results_dir / "run_info.yaml", args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
