#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

import yaml


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Write runtime inputs for the methylation_array_analysis template.")
    parser.add_argument("--workspace-dir", default=".")
    parser.add_argument("--project-dir", default=".")
    parser.add_argument("--results-dir", default="./results")
    parser.add_argument("--authors", default="")
    return parser.parse_args()


def r_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def derive_authors(explicit_authors: str, project_dir: Path) -> str:
    if explicit_authors.strip():
        return explicit_authors.strip()
    project_file = project_dir / "project.yaml"
    if not project_file.exists():
        return ""
    try:
        data = yaml.safe_load(project_file.read_text(encoding="utf-8")) or {}
    except Exception:
        return ""
    author = data.get("author") or {}
    if not isinstance(author, dict):
        return ""
    name = str(author.get("name") or "").strip()
    if name:
        return name
    organization = str(author.get("organization") or "").strip()
    return organization


def main() -> int:
    args = parse_args()
    workspace_dir = Path(args.workspace_dir).resolve()
    project_dir = Path(args.project_dir).resolve()
    results_dir = Path(args.results_dir).resolve()
    workspace_dir.mkdir(parents=True, exist_ok=True)
    results_dir.mkdir(parents=True, exist_ok=True)

    project_name = project_dir.name
    authors = derive_authors(args.authors, project_dir)

    inputs_lines = [
        "# Auto-generated by build_dnam_inputs.py",
        f'workspace_dir <- {r_string(str(workspace_dir))}',
        f'project_dir <- {r_string(str(project_dir))}',
        f'project_name <- {r_string(project_name)}',
        f'results_dir <- {r_string(str(results_dir))}',
        f'authors <- {r_string(authors)}',
        'dir.create(results_dir, recursive = TRUE, showWarnings = FALSE)',
        "",
    ]
    (workspace_dir / "dnam_inputs.R").write_text("\n".join(inputs_lines), encoding="utf-8")

    run_info = {
        "project_dir": str(project_dir),
        "workspace_dir": str(workspace_dir),
        "results_dir": str(results_dir),
        "params": {
            "authors": authors,
            "project_name": project_name,
        },
    }
    (results_dir / "run_info.yaml").write_text(yaml.safe_dump(run_info, sort_keys=False), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
