#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Materialize resolved Linkar inputs for the miRNA analysis workspace.")
    parser.add_argument("--workspace-dir", required=True)
    parser.add_argument("--results-dir", required=True)
    parser.add_argument("--counts-file", required=True)
    parser.add_argument("--hairpin-counts-file", default="")
    parser.add_argument("--samplesheet", required=True)
    parser.add_argument("--organism", required=True)
    parser.add_argument("--name", default="")
    parser.add_argument("--authors", default="")
    return parser.parse_args()


def existing_file(value: str, label: str, required: bool = True) -> str:
    if not value.strip():
        if required:
            raise SystemExit(f"{label} is required.")
        return ""
    path = Path(value).expanduser().resolve()
    if not path.is_file():
        raise SystemExit(f"{label} does not exist: {path}")
    return str(path)


def r_assignment(name: str, value: str) -> str:
    return f"{name} <- {json.dumps(value, ensure_ascii=False)}"


def main() -> int:
    args = parse_args()
    workspace = Path(args.workspace_dir).resolve()
    results = Path(args.results_dir).resolve()
    workspace.mkdir(parents=True, exist_ok=True)
    results.mkdir(parents=True, exist_ok=True)

    counts_file = existing_file(args.counts_file, "counts_file")
    hairpin_counts_file = existing_file(args.hairpin_counts_file, "hairpin_counts_file", required=False)
    samplesheet = existing_file(args.samplesheet, "samplesheet")
    values = {
        "workspace_dir": str(workspace),
        "results_dir": str(results),
        "counts_file": counts_file,
        "hairpin_counts_file": hairpin_counts_file,
        "samplesheet_path": samplesheet,
        "organism": args.organism.strip(),
        "project_name": args.name.strip() or workspace.parent.name,
        "authors": args.authors.strip(),
    }
    (workspace / "mirna_inputs.R").write_text(
        "# Generated by build_mirna_inputs.py. Do not edit.\n"
        + "\n".join(r_assignment(key, value) for key, value in values.items())
        + "\n",
        encoding="utf-8",
    )
    run_info = {
        "template": "mirna_differential",
        "template_version": "0.1.0",
        "params": {
            "counts_file": counts_file,
            "hairpin_counts_file": hairpin_counts_file,
            "samplesheet": samplesheet,
            "organism": values["organism"],
            "name": values["project_name"],
            "authors": values["authors"],
        },
    }
    (results / "run_info.yaml").write_text(
        json.dumps(run_info, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
