#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import shlex
import shutil
from pathlib import Path


GENOME_PLACEHOLDER = "__EDIT_ME_GENOME__"
MIRTRACE_SPECIES_BY_GENOME = {
    "GRCh38": "hsa",
    "GRCm39": "mmu",
    "mRatBN7.2": "rno",
    "Sscrofa11.1": "ssc",
    "GRCg7b": "gga",
}
TRUTHY_VALUES = {"1", "true", "yes", "on"}
FALSY_VALUES = {"0", "false", "no", "off", "none", "null", "na", "n/a", ""}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prepare the nf-core/smrnaseq workspace.")
    parser.add_argument(
        "--prepare",
        "--prepare-only",
        action="store_true",
        help="Copy samplesheet.csv and write config/run_params.env.",
    )
    return parser.parse_args()


def require_env(name: str) -> str:
    value = os.environ.get(name, "").strip()
    if not value:
        raise SystemExit(f"[error] required environment variable is missing: {name}")
    return value


def optional_env(name: str, default: str = "") -> str:
    return os.environ.get(name, default).strip()


def normalize_bool(value: str, *, name: str) -> str:
    lowered = value.strip().lower()
    if lowered in TRUTHY_VALUES:
        return "true"
    if lowered in FALSY_VALUES:
        return "false"
    raise SystemExit(f"[error] {name} must be true or false, got: {value}")


def normalize_memory(value: str) -> str:
    memory = value.strip()
    if memory.upper().endswith("GB"):
        return f"{memory[:-2]}.GB"
    return memory


def shell_assign(name: str, value: str) -> str:
    return f"{name}={shlex.quote(value)}"


def copy_samplesheet(source: Path, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    if source.resolve() != destination.resolve():
        shutil.copy2(source, destination)


def validate_samplesheet(path: Path) -> None:
    header = path.read_text(encoding="utf-8").splitlines()[0].lstrip("\ufeff") if path.stat().st_size else ""
    if header.replace(" ", "") != "sample,fastq_1,fastq_2":
        raise SystemExit("[error] samplesheet header must be exactly: sample,fastq_1,fastq_2")


def validate_mirtop_annotation(path: Path) -> None:
    recognized_markers = ("miRBase", "MirGeneDB", "microRNAs")
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            if not line.startswith("#"):
                break
            if any(marker in line for marker in recognized_markers):
                return
    raise SystemExit(
        "[error] MIRNA_GTF header does not identify a miRTop-compatible database "
        "(expected miRBase, MirGeneDB, or microRNAs)"
    )


def write_resource_config(path: Path, *, max_cpus: str, max_memory: str) -> None:
    limits: list[str] = []
    if max_cpus:
        limits.append(f"        cpus: {int(max_cpus)}")
    if max_memory:
        limits.append(f"        memory: {max_memory}")
    path.parent.mkdir(parents=True, exist_ok=True)
    if not limits:
        path.write_text("// No facility resource limits were resolved.\n", encoding="utf-8")
        return
    body = ",\n".join(limits)
    path.write_text(
        "// Generated by run.py. Limits are applied per process.\n"
        "process {\n"
        "    resourceLimits = [\n"
        f"{body}\n"
        "    ]\n"
        "}\n",
        encoding="utf-8",
    )


def prepare() -> None:
    script_dir = Path(__file__).resolve().parent
    source_samplesheet = Path(require_env("SAMPLESHEET")).resolve()
    validate_samplesheet(source_samplesheet)
    copy_samplesheet(source_samplesheet, script_dir / "samplesheet.csv")

    genome = require_env("GENOME")
    mirtrace_species = optional_env("MIRTRACE_SPECIES") or MIRTRACE_SPECIES_BY_GENOME.get(genome, "")

    values = {
        "GENOME": genome,
        "MIRTRACE_SPECIES": mirtrace_species,
        "MIRNA_GTF": optional_env("MIRNA_GTF"),
        "MATURE": optional_env("MATURE"),
        "HAIRPIN": optional_env("HAIRPIN"),
        "THREE_PRIME_ADAPTER": optional_env(
            "THREE_PRIME_ADAPTER", "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"
        ),
        "WITH_UMI": normalize_bool(optional_env("WITH_UMI", "false"), name="with_umi"),
        "UMITOOLS_EXTRACT_METHOD": optional_env("UMITOOLS_EXTRACT_METHOD", "string"),
        "UMITOOLS_BC_PATTERN": optional_env("UMITOOLS_BC_PATTERN"),
        "SKIP_UMI_EXTRACT_BEFORE_DEDUP": normalize_bool(
            optional_env("SKIP_UMI_EXTRACT_BEFORE_DEDUP", "true"),
            name="skip_umi_extract_before_dedup",
        ),
        "SAVE_REFERENCE": normalize_bool(optional_env("SAVE_REFERENCE", "true"), name="save_reference"),
        "SAVE_INTERMEDIATES": normalize_bool(
            optional_env("SAVE_INTERMEDIATES", "false"), name="save_intermediates"
        ),
        "MAX_CPUS": optional_env("MAX_CPUS"),
        "MAX_MEMORY": normalize_memory(optional_env("MAX_MEMORY")),
    }
    reference_values = [values["MIRNA_GTF"], values["MATURE"], values["HAIRPIN"]]
    if any(reference_values) and not all(reference_values):
        raise SystemExit("[error] MIRNA_GTF, MATURE, and HAIRPIN must be set together")
    for reference in reference_values:
        if reference and not Path(reference).is_file():
            raise SystemExit(f"[error] miRNA reference file does not exist: {reference}")
    if values["MIRNA_GTF"]:
        validate_mirtop_annotation(Path(values["MIRNA_GTF"]))
    if values["GENOME"] == GENOME_PLACEHOLDER:
        print("[warn] genome is unresolved; edit config/run_params.env before running", flush=True)
    if values["WITH_UMI"] == "true" and not values["UMITOOLS_EXTRACT_METHOD"]:
        raise SystemExit("[error] umitools_extract_method is required when with_umi=true")

    write_resource_config(
        script_dir / "config" / "resources.config",
        max_cpus=values["MAX_CPUS"],
        max_memory=values["MAX_MEMORY"],
    )

    run_params = script_dir / "config" / "run_params.env"
    run_params.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Generated by run.py. Edit values here before rerunning."]
    lines.extend(shell_assign(name, value) for name, value in values.items())
    lines.append("")
    run_params.write_text("\n".join(lines), encoding="utf-8")
    print(f"[info] wrote {run_params.relative_to(script_dir)}", flush=True)


def main() -> int:
    parse_args()
    prepare()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
